### ISSUE TITLE
Feature idea - Soft deletes

### ISSUE THREAD

**Issue by Harry-Torry** [ThisVessel/Caravel#4]
Are soft deletes (and maybe even a trash bin etc) out of the scope for this project?

**Comment by JesseLeite** [comment]
Absolutely!  You can add soft deletes in your migrations/models already.  I just need to add UI into Caravel to view deleted/trash.  Should probably hook that into ability/policy checks too.  Great idea though.

**Comment by JesseLeite** [comment]
Done!  All you need to do is add `$table->softDeletes()` in your migration, and use `SoftDeletes` trait on your model, as per Laravel docs.  If Caravel detects soft deletes on the model, you'll see these options:

![example](https://beemapp.s3-eu-west-1.amazonaws.com/08fda827-c3e9-4df8-9460-5029bb714fbe.jpg)
